language: android

android:
  components:
    - tools
    - platform-tools

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"

jdk:
  - oraclejdk8

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2